LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE    := SerialAPI
LOCAL_SRC_FILES :=  SerialAPI.c 
LOCAL_ALLOW_UNDEFINED_SYMBOLS := true
LOCAL_LDLIBS := -llog

include $(BUILD_SHARED_LIBRARY)
